name: Health Checks CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  build:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Trigger ADO pipeline with build-id output variable
        id: ado
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/hpc-platform-team/hpc-vm-health-check-framework'
          azure-pipeline-name: 'hpc-vm-health-check-framework'
          azure-pipeline-variables: '{ "GITHUB_PR_NUMBER": "${{ github.event.number }}" }'
          azure-devops-token: '${{ secrets.ADO_TOKEN }}'
          
      - name: echo output from previus step
        run: echo ${{ toJson(steps.ado.outputs) }}

      - name: Sleep for 30 seconds
        run: sleep 30

      - name: Get status
        run: |
          # Wait until build finishes
          build_status=$(get_builds_res | jq -r ".status")
        
          while [ "${build_status}" != "completed" ]
          do
              build_status=$(get_builds_res | jq -r ".status")
            
              echo "Build status: ${build_status}"
              sleep 300
          done
          
          build_res=$(get_builds_res | jq -r ".result")
          echo "Build result: ${build_res}"
          
          # Throw an error if build fails
          if [ "${build_res}" != "succeeded" ]
          then
              echo "Error! Build failed..."
              exit 1
          fi