name: Health Checks CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - main
      - releases/*

jobs:
  build:
    name: Unit tests

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@v3
      
      - name: Trigger ADO pipeline
        uses: Azure/pipelines@v1.2
        with:
          azure-devops-project-url: 'https://dev.azure.com/hpc-platform-team/hpc-vm-health-check-framework'
          azure-pipeline-name: 'hpc-vm-health-check-framework'
          azure-pipeline-variables: '{ "GITHUB_PR_NUMBER": "${{ github.event.number }}", "GITHUB_SHA": "${{ github.sha}}" }'
          azure-devops-token: '${{ secrets.ADO_TOKEN }}'

      - name: Sleep for 30 seconds
        run: sleep 30
          
      - name: echo ADO build status
        run: echo ${{ steps.ado.outputs.url-response }}
