name: Health Checks CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: unit tests

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: print contents in parent directory
        run: ls -la ../
      
      - name: Trigger ADO pipeline
        uses: Azure/pipelines@v1
        with:
          azure-devops-project-url: https://dev.azure.com/hpc-platform-team/hpc-vm-health-check-framework/_build?definitionId=29
          azure-devops-token: ${{ secrets.GITHUB_TOKEN }}