name: Health Checks CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: unit tests

    runs-on: ubuntu-latest

    steps:
      - name: run testscript.sh
        run: bash testscript.sh