name: Health Checks CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: unit tests

    runs-on: ubuntu-latest

    steps:
      - name: print contents in parent directory
        run: ls -la ../

      - name: give permissions and run testscript.sh
        run: chmod +x ../testscript.sh && ../testscript.sh