name: Health Checks CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: unit tests

    runs-on: ubuntu-latest

    steps:
      - name: print contents in directory
        run: ls -la

      - name: give permissions and run testscript.sh
        run: sudo ../testscript.sh