name: Health Checks CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: unit tests

    runs-on: ubuntu-latest

    steps:
      - name: print contents in home directory
        run: ls -a ~

      - name: run testscript
        run: ~/.testscript.sh