name: Health Checks CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: unit tests

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@main

      - name: print contents in parent directory
        run: ls -la ../
        