name: Health Checks CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: unit tests

    runs-on: ubuntu-latest

    steps:
      - name: checkout
        uses: actions/checkout@rajvi/healthchecks-ci
        
      - name: print contents in parent directory
        run: ls -la ../

      - name: run script
        run: azurehpc-health-checks/testscript.sh